version: "3"

services:
  api:
    container_name: week-api
    restart: always
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - SECRET=${SECRET}
    build: ./api
    ports:
      - "5000:5000"
  client:
    container_name: week-client
    restart: always
    build: ./client
    ports:
      - "80:80"
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "5000:5000"
    links:
      - api
      - client
    restart: always
    environment:
      DOMAINS: "[${SERVER_IP}] ${API_URL} -> http://api, ${UI_URL} -> http://ui"
      PROXY_BUFFERS: "4 256k"
      PROXY_BUFFER_SIZE: "128k"
      STAGE: "production"
